replicaCount: 1

portal:
  enabled: true
  card:
    icon: fa-cubes
  overview:
    enabled: true
    text: pgsql overview text
  compositionstatus:
    enabled: true
  applicationstatus:
    enabled: true
  terminal:
    enabled: false
  events:
    enabled: true
  yamlviewer:
    enabled: true