---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: petclinic
  labels:
    app: visits-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: visits-service