apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    # tls:
    #   selfSignedCertificate:
    #     disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
            requests:
              memory: 250Mi
              cpu: 100m
            limits:
              cpu: 500m