---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: petclinic-vets-service-destination
  namespace: petclinic
spec:
  host: vets-service.petclinic.svc.cluster.local
  subsets:
  - name: prod
    labels:
      version: prod
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: petclinic-vets-service-routes
  namespace: petclinic
spec:
  hosts:
  - "*"
  gateways:
  - main-gateway
  http:
    - match:
      - uri:
          prefix: "/api/vet/"
      rewrite:
        uri: "/"
      route:
      - destination:
          host: vets-service.petclinic.svc.cluster.local
          port:
            number: 8080
          subset: prod