apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


# replicas:
#   - name: petclinic-frontend
#     count: 3

nameSuffix: "-baseline"

commonLabels:
  version: baseline