---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spin-installer-pvc
  namespace: spinnaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-installer
  template:
    metadata:
      labels:
        app: spin-installer
    spec:
      serviceAccountName: spin-clouddriver-sa
      restartPolicy: Always
      volumes:
        - name: spin-home
          persistentVolumeClaim:
            claimName: spin-installer-pvc
        - name: spin-apps
          configMap:
            name: apps
        - name: spin-pipelines
          configMap:
            name: pipelines
        - name: spin-canary-configs
          configMap:
            name: canary-configs
        - name: spin-templates
          configMap:
            name: templates
        - name: spin-kubeconfigs
          configMap:
            name: kubeconfigs
      containers:
      - name: halyard
        image: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: spin-home
            mountPath: /home/spinnaker
          - name: spin-kubeconfigs
            mountPath: "/home/spinnaker/kubeconfigs"
            readOnly: true
        env:
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: gh-token
              key: password
        - name: JENKINS_USR
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: jenkins-admin-user
        - name: JENKINS_PASS
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: jenkins-admin-password
        - name: JENKINS_EP
          value: "http://jenkins:8080"
        # - name: DOCKER_USR
        #   valueFrom:
        #     secretKeyRef:
        #       name: docker-credentials
        #       key: username
        # - name: DOCKER_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: docker-credentials
        #       key: password
        # - name: DOCKER_EP
        #   value: "index.docker.io"
        # - name: MINIO_SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: minio
        #       key: root-password
        # - name: MINIO_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: minio
        #       key: root-user
        # - name: MINIO_EP
        #   value: "http://minio:9000"
      - name: spin-cli
        image: us-docker.pkg.dev/spinnaker-community/docker/spin
        command: ["sh", "-c"]
        args: ["sleep infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: spin-apps
          mountPath: "/home/spinnaker/apps"
          readOnly: true
        - name: spin-pipelines
          mountPath: "/home/spinnaker/pipelines"
          readOnly: true
        - name: spin-canary-configs
          mountPath: "/home/spinnaker/canary-configs"
          readOnly: true
        - name: spin-templates
          mountPath: "/home/spinnaker/templates"
          readOnly: true
---
apiVersion: v1
kind: Service                                                                                                                                                                                 
metadata:                                                                                                                                                                                                                                                                                                                                     
  labels:                                                                                                                                                                                     
    app: spin                                                                                                                                                                                 
    cluster: spin-gate                                                                                                                                                                        
  name: spin-gate-lb                                                                                                                                                                         
  namespace: spinnaker                                                                                                                                                                                                                                                                                                                       
spec:                                                                                                                                                                                                                                                                                                                                                     
  ports:                                                                                                                                                                                      
  - port: 8084                                                                                                                                                                                
    protocol: TCP                                                                                                                                                                             
    targetPort: 8084                                                                                                                                                                          
  selector:                                                                                                                                                                                   
    app: spin                                                                                                                                                                                 
    cluster: spin-gate                                                                                                                                                                                                                                                                                                                                              
  type: LoadBalancer
---
apiVersion: v1                                                                                                                                                                                
kind: Service                                                                                                                                                                                 
metadata:                                                                                                                                                                                     
  labels:                                                                                                                                                                                     
    app: spin                                                                                                                                                                                 
    cluster: spin-deck                                                                                                                                                                      
  name: spin-deck-lb                                                                                                                                                                        
  namespace: spinnaker                                                                                                                                                                                                                                                                                                       
spec:                                                                                                                                                                                                                                                                                                                                                       
  ports:                                                                                                                                                                                      
  - port: 9000                                                                                                                                                                                
    protocol: TCP                                                                                                                                                                             
    targetPort: 9000                                                                                                                                                                          
  selector:                                                                                                                                                                                   
    app: spin                                                                                                                                                                                 
    cluster: spin-deck                                                                                                                                                                                                                                                                                                                                            
  type: LoadBalancer