---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic
  labels:
    app: customers-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: customers-service